[package]
name = "privacypass"
version = "0.1.0"
edition = "2021"
description = "WIP implementation of Privacy Pass"
license = "MIT"
documentation = "https://docs.rs/privacypass"
repository = "https://github.com/raphaelrobert/privacypass"
readme = "README.md"
keywords = ["privacy pass", "privacypass", "privacy", "pass"]
categories = ["cryptography", "privacy"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-trait = "0.1.56"
base64 = "0.21.0"
generic-array = "0.14.5"
rand = "0.8.5"
serde = "1.0.138"
sha2 = "0.10.2"
thiserror = "1.0.31"
tls_codec = "0.2.0"
voprf = "0.5.0-pre.1"
p384 = { version = "0.13.0-pre", default-features = false, features = [
  "hash2curve",
  "voprf",
] }
blind-rsa-signatures = "0.14.1"
pest = "2.2.1"
pest_derive = "2.2.1"
tls_codec_derive = "0.2.0"
http = "0.2.8"
typenum = "1.15.0"

[features]
default = []
kat = ["voprf/danger"]

[dev-dependencies]
privacypass = { path = ".", features = ["kat"] }
tokio = { version = "1.20.0", features = ["full"] }
criterion = { version = "0.4.0", features = ["async_futures", "async_tokio"] }


[[bench]]
name = "benchmark"
harness = false

[patch.crates-io]
voprf = { git = "https://github.com/khonsulabs/voprf",  branch = "p384"  }
p384 = { git = "https://github.com/khonsulabs/elliptic-curves", branch = "elliptic-curve-0.13.0-pre.4" }
