[package]
name = "privacypass"
version = "0.1.0"
edition = "2021"
description = "WIP implementation of Privacy Pass"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
